version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    volumes:
      - ~$USER/elasticsearch:/usr/share/elasticsearch/data
  fluentd:
    build: fluentd/
    links:
      - elasticsearch
    ports:
      - '24224:24224'
  kibana:
    image: kibana:latest
    links:
      - elasticsearch
    ports:
      - '5601:5601'
